nome = str(input('Digite seu nome completo: ')).strip().upper()
separa = nome.split()
print('Muinto prazer em te conheçer!')
print('Seu primeiro nome é: {}'.format(separa[0]))
print('Seu ultimo nome é: {}'.format(separa[len(separa)-1]))
