nome = str(input('Qual seu nome completo?: ').strip())
print('Analizando seu nome...')
print('Seu nome em maiúsculas é: {}' .format(nome.upper()))
print('Seu nome em minusculas é: {}' .format(nome.lower()))
print('Seu nome ao todo tem {} letras' .format(len(nome) - nome.count(' ')))
separar = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras' .format(separar[0], len(separar[0])))
